name: foodb
description: A CouchDB warpper with dart implementation
version: 0.12.0
repository: https://github.com/feedmepos/foodb 

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  http: ^1.1.0
  json_annotation: ^4.0.1
  uri: ^1.0.0
  uuid: ^4.0.0
  crypto: ^3.0.1
  collection: ^1.15.0
  synchronized: ^3.0.0+2
  web_socket_channel: ^2.2.0

dev_dependencies:
  build_runner: ^2.0.0
  json_serializable: ^4.1.3
  path: any
  test: any
